version: '3'

services:

  tf_serving_server:
    container_name: tf_serving_server
    image: $USER/tensorflow-serving-devel-cpu:latest
    command: /root/serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=gan --model_base_path=/root/serving/gan-export &> gan_log &
    networks:
      - tf_serving
    ports:
      - "9000:9000"

  tf_serving_client:
    container_name: tf_serving_client
    image: $USER/tensorflow-serving-client:latest
    networks:
      - tf_serving
    ports:
      - "5001:5001"
    environment:
      - TF_SERVER_NAME=tf_serving_server
      - TF_SERVER_PORT=5001
    depends_on:
      - tf_serving_server

networks:
  tf_serving:
    driver: bridge